# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "widen"
    target-branch: "1.1.x"
    commit-message:
      include: "scope"
      prefix: "composer"
    ignore:
      - dependency-name: "rollbar/rollbar"
        versions:
          - ">= 3"
      - dependency-name: "predis/predis"
        versions:
          - ">= 2"
      - dependency-name: "elasticsearch/elasticsearch"
        versions:
          - ">= 8"
      - dependency-name: "laminas/laminas-dependency-plugin"
        versions:
          - ">= 2.3.0"
      - dependency-name: "mimmi20/monolog-streamformatter"
        versions:
          - ">= 2"
      - dependency-name: "symfony/mailer"
        versions:
          - ">= 0"
      - dependency-name: "symfony/mime"
        versions:
          - ">= 0"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "1.1.x"
    commit-message:
      include: "scope"
      prefix: "github-actions"
